monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                # Handler for logging to the main
                type: rotating_file
                path: "%kernel.logs_dir%/app-debug.log"
                date_format: 'Y-m-d'
              #  formatter: monolog.formatter.custom_formatter
                level: debug

            # Handler for logging to the console
            console:
                type: rotating_file
                path: "%kernel.logs_dir%/app-info.log"
                date_format: 'Y-m-d'
             #   formatter: monolog.formatter.custom_formatter
                level: info

            # Handler for logging critical errors to a separate file
            critical:
                type: rotating_file
                path: "%kernel.logs_dir%/app-critical.log"
                date_format: 'Y-m-d'
            #    formatter: monolog.formatter.custom_formatter
                level: critical

            warning:
                type: rotating_file
                path: "%kernel.logs_dir%/app-warning.log"
                date_format: 'Y-m-d'
            #   formatter: monolog.formatter.custom_formatter
                level: warning


        #formatters:
         #   custom_formatter:
          #      type: line
                #format: "[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n"
           #     date_format: "Y-m-d h:i:s A"  # Custom date format (Year-Month-Day Hour:Minute:Second AM/PM)

            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
           ## console:
           ##     type: console
           ##     process_psr_3_messages: false
           ##     channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
